# fly.toml app configuration file generated for icy-backend-dev on 2025-02-11T11:30:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icy-backend-dev'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.23.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
