version: "0.5"

processes:
  postgresql:
    command: "pg_ctl start -D ./data/dev -l ./data/dev/logfile -o '-p 25432'"
    shutdown:
      command: "pg_ctl stop -D ./data/dev -m fast"
    is_daemon: true
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "pg_ctl status -D ./data/dev"

  postgresql_test:
    command: "pg_ctl start -D ./data/test -l ./data/test/logfile -o '-p 35432'"
    shutdown:
      command: "pg_ctl stop -D ./data/test -m fast"
    is_daemon: true
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "pg_ctl status -D ./data/test"
